language: java
install: mvn clean install -s support/settings.xml -DskipTests=true 
script: mvn test verify -s support/settings.xml 
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  irc: "irc.freenode.org#dynjs"

